/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107372-geb7ab3928f-20220712"
#endif /* AVUTIL_FFVERSION_H */
